name: Agricultura Urbana
favicon: null
layout_spectrum: 0.7297872
typography_spectrum: 0.5610648
title: Agricultura Urbana Ecuador
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFF2E9'
    - '#5579C3'
    - '#65584F'
    - '#A0C1EE'
    - '#9A8979'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
