typography_spectrum: 0.5610648
color:
  brandColors:
    - '#FFF2E9'
    - '#5579C3'
    - '#65584F'
    - '#A0C1EE'
    - '#9A8979'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.48772
analytics:
  google: null
  facebook: null
  twitter: null
name: Agricultura Urbana
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Quienes somos
    id: 53a4d92f-2898-478a-8be8-010bc7c217ba
    type: content
  - name: Contacto
    id: 51dac73c-5cef-4783-86c3-e9aae5ec1d2f
    type: content
favicon: null
title: Agricultura Urbana Ecuador
purpose: []
