layout_spectrum: 0.7297872
color:
  saturation: 0.3382979
  lightness: 0.6344059
  brandStrength: 0.4575316
  brandColors:
    - '#FFF2E9'
    - '#5579C3'
    - '#65584F'
    - '#A0C1EE'
    - '#9A8979'
  rhythmicContrast: 0.3490903
typography_spectrum: 0.5610648
name: Agricultura Urbana
